CREATE TABLE mdm_production_site (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(32) NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
 version BIGINT NOT NULL DEFAULT 0, created_by VARCHAR(100) NOT NULL, created_at DATETIME(6) NOT NULL,
 CHECK(status IN ('ENABLED','DISABLED'))
);
